FROM ansible/centos7-ansible

MAINTAINER menard menard99@qq.com 2019-04-19

RUN yum -y install python34 && \
    ln -s /usr/bin/python3.4 /usr/bin/python3 && \
    ln -s /usr/bin/python3.4m /usr/bin/python3m
