FROM centos:centos7

MAINTAINER menard menard99@qq.com 2019-04-19

RUN yum clean all && \
    yum -y install epel-release && \
    yum -y install PyYAML python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip && \
	yum -y install python34 --nogpgcheck && \
    mkdir /etc/ansible/ && \
	echo '[local]\nlocalhost\n' > /etc/ansible/hosts && \
	mkdir /opt/ansible/ && \
	git clone https://github.com/ansible/ansible.git /opt/ansible/ansible && \
	git submodule update --init
	
WORKDIR /opt/ansible/ansible

ENV PATH /opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin
ENV PYTHONPATH /opt/ansible/ansible/lib
ENV ANSIBLE_LIBRARY /opt/ansible/ansible/librar
